# Generated by Django 4.2 on 2023-04-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
